/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BurnMintTokenPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "addRemotePool"
      | "applyAllowListUpdates"
      | "applyChainUpdates"
      | "getAllowList"
      | "getAllowListEnabled"
      | "getCurrentInboundRateLimiterState"
      | "getCurrentOutboundRateLimiterState"
      | "getRateLimitAdmin"
      | "getRemotePools"
      | "getRemoteToken"
      | "getRmnProxy"
      | "getRouter"
      | "getSupportedChains"
      | "getToken"
      | "getTokenDecimals"
      | "isRemotePool"
      | "isSupportedChain"
      | "isSupportedToken"
      | "owner"
      | "supportsInterface"
      | "typeAndVersion"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllowListAdd"
      | "AllowListRemove"
      | "Burned"
      | "ChainAdded"
      | "ChainConfigured"
      | "ChainRemoved"
      | "ConfigChanged"
      | "Locked"
      | "Minted"
      | "OwnershipTransferRequested"
      | "OwnershipTransferred"
      | "RateLimitAdminSet"
      | "Released"
      | "RemotePoolAdded"
      | "RemotePoolRemoved"
      | "RouterUpdated"
      | "TokensConsumed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRemotePool",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "applyAllowListUpdates",
    values: [AddressLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "applyChainUpdates",
    values: [
      BigNumberish[],
      {
        remoteChainSelector: BigNumberish;
        remotePoolAddresses: BytesLike[];
        remoteTokenAddress: BytesLike;
        outboundRateLimiterConfig: {
          isEnabled: boolean;
          capacity: BigNumberish;
          rate: BigNumberish;
        };
        inboundRateLimiterConfig: {
          isEnabled: boolean;
          capacity: BigNumberish;
          rate: BigNumberish;
        };
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowListEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentInboundRateLimiterState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentOutboundRateLimiterState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRateLimitAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemotePools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemoteToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRmnProxy",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getRouter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSupportedChains",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTokenDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRemotePool",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupportedChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "typeAndVersion",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRemotePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyAllowListUpdates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyChainUpdates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowListEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentInboundRateLimiterState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentOutboundRateLimiterState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRateLimitAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemotePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemoteToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRmnProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRemotePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSupportedChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "typeAndVersion",
    data: BytesLike
  ): Result;
}

export namespace AllowListAddEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowListRemoveEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BurnedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainAddedEvent {
  export type InputTuple = [
    remoteChainSelector: BigNumberish,
    remoteToken: BytesLike,
    outboundRateLimiterConfig: {
      isEnabled: boolean;
      capacity: BigNumberish;
      rate: BigNumberish;
    },
    inboundRateLimiterConfig: {
      isEnabled: boolean;
      capacity: BigNumberish;
      rate: BigNumberish;
    }
  ];
  export type OutputTuple = [
    remoteChainSelector: bigint,
    remoteToken: string,
    outboundRateLimiterConfig: [
      isEnabled: boolean,
      capacity: bigint,
      rate: bigint
    ] & { isEnabled: boolean; capacity: bigint; rate: bigint },
    inboundRateLimiterConfig: [
      isEnabled: boolean,
      capacity: bigint,
      rate: bigint
    ] & { isEnabled: boolean; capacity: bigint; rate: bigint }
  ];
  export interface OutputObject {
    remoteChainSelector: bigint;
    remoteToken: string;
    outboundRateLimiterConfig: [boolean, bigint, bigint] & {
      isEnabled: boolean;
      capacity: bigint;
      rate: bigint;
    };
    inboundRateLimiterConfig: [boolean, bigint, bigint] & {
      isEnabled: boolean;
      capacity: bigint;
      rate: bigint;
    };
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainConfiguredEvent {
  export type InputTuple = [
    remoteChainSelector: BigNumberish,
    outboundRateLimiterConfig: {
      isEnabled: boolean;
      capacity: BigNumberish;
      rate: BigNumberish;
    },
    inboundRateLimiterConfig: {
      isEnabled: boolean;
      capacity: BigNumberish;
      rate: BigNumberish;
    }
  ];
  export type OutputTuple = [
    remoteChainSelector: bigint,
    outboundRateLimiterConfig: [
      isEnabled: boolean,
      capacity: bigint,
      rate: bigint
    ] & { isEnabled: boolean; capacity: bigint; rate: bigint },
    inboundRateLimiterConfig: [
      isEnabled: boolean,
      capacity: bigint,
      rate: bigint
    ] & { isEnabled: boolean; capacity: bigint; rate: bigint }
  ];
  export interface OutputObject {
    remoteChainSelector: bigint;
    outboundRateLimiterConfig: [boolean, bigint, bigint] & {
      isEnabled: boolean;
      capacity: bigint;
      rate: bigint;
    };
    inboundRateLimiterConfig: [boolean, bigint, bigint] & {
      isEnabled: boolean;
      capacity: bigint;
      rate: bigint;
    };
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainRemovedEvent {
  export type InputTuple = [remoteChainSelector: BigNumberish];
  export type OutputTuple = [remoteChainSelector: bigint];
  export interface OutputObject {
    remoteChainSelector: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfigChangedEvent {
  export type InputTuple = [
    config: { isEnabled: boolean; capacity: BigNumberish; rate: BigNumberish }
  ];
  export type OutputTuple = [
    config: [isEnabled: boolean, capacity: bigint, rate: bigint] & {
      isEnabled: boolean;
      capacity: bigint;
      rate: bigint;
    }
  ];
  export interface OutputObject {
    config: [boolean, bigint, bigint] & {
      isEnabled: boolean;
      capacity: bigint;
      rate: bigint;
    };
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintedEvent {
  export type InputTuple = [
    sender: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [sender: string, recipient: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferRequestedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateLimitAdminSetEvent {
  export type InputTuple = [rateLimitAdmin: AddressLike];
  export type OutputTuple = [rateLimitAdmin: string];
  export interface OutputObject {
    rateLimitAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [
    sender: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [sender: string, recipient: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemotePoolAddedEvent {
  export type InputTuple = [
    remoteChainSelector: BigNumberish,
    remotePoolAddress: BytesLike
  ];
  export type OutputTuple = [
    remoteChainSelector: bigint,
    remotePoolAddress: string
  ];
  export interface OutputObject {
    remoteChainSelector: bigint;
    remotePoolAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemotePoolRemovedEvent {
  export type InputTuple = [
    remoteChainSelector: BigNumberish,
    remotePoolAddress: BytesLike
  ];
  export type OutputTuple = [
    remoteChainSelector: bigint,
    remotePoolAddress: string
  ];
  export interface OutputObject {
    remoteChainSelector: bigint;
    remotePoolAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouterUpdatedEvent {
  export type InputTuple = [oldRouter: AddressLike, newRouter: AddressLike];
  export type OutputTuple = [oldRouter: string, newRouter: string];
  export interface OutputObject {
    oldRouter: string;
    newRouter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensConsumedEvent {
  export type InputTuple = [tokens: BigNumberish];
  export type OutputTuple = [tokens: bigint];
  export interface OutputObject {
    tokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BurnMintTokenPool extends BaseContract {
  connect(runner?: ContractRunner | null): BurnMintTokenPool;
  waitForDeployment(): Promise<this>;

  interface: BurnMintTokenPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  addRemotePool: TypedContractMethod<
    [remoteChainSelector: BigNumberish, remotePoolAddress: BytesLike],
    [void],
    "nonpayable"
  >;

  applyAllowListUpdates: TypedContractMethod<
    [removes: AddressLike[], adds: AddressLike[]],
    [void],
    "nonpayable"
  >;

  applyChainUpdates: TypedContractMethod<
    [
      remoteChainSelectorsToRemove: BigNumberish[],
      chainsToAdd: {
        remoteChainSelector: BigNumberish;
        remotePoolAddresses: BytesLike[];
        remoteTokenAddress: BytesLike;
        outboundRateLimiterConfig: {
          isEnabled: boolean;
          capacity: BigNumberish;
          rate: BigNumberish;
        };
        inboundRateLimiterConfig: {
          isEnabled: boolean;
          capacity: BigNumberish;
          rate: BigNumberish;
        };
      }[]
    ],
    [void],
    "nonpayable"
  >;

  getAllowList: TypedContractMethod<[], [string[]], "view">;

  getAllowListEnabled: TypedContractMethod<[], [boolean], "view">;

  getCurrentInboundRateLimiterState: TypedContractMethod<
    [remoteChainSelector: BigNumberish],
    [
      [bigint, bigint, boolean, bigint, bigint] & {
        tokens: bigint;
        lastUpdated: bigint;
        isEnabled: boolean;
        capacity: bigint;
        rate: bigint;
      }
    ],
    "view"
  >;

  getCurrentOutboundRateLimiterState: TypedContractMethod<
    [remoteChainSelector: BigNumberish],
    [
      [bigint, bigint, boolean, bigint, bigint] & {
        tokens: bigint;
        lastUpdated: bigint;
        isEnabled: boolean;
        capacity: bigint;
        rate: bigint;
      }
    ],
    "view"
  >;

  getRateLimitAdmin: TypedContractMethod<[], [string], "view">;

  getRemotePools: TypedContractMethod<
    [remoteChainSelector: BigNumberish],
    [string[]],
    "view"
  >;

  getRemoteToken: TypedContractMethod<
    [remoteChainSelector: BigNumberish],
    [string],
    "view"
  >;

  getRmnProxy: TypedContractMethod<[], [string], "view">;

  getRouter: TypedContractMethod<[], [string], "view">;

  getSupportedChains: TypedContractMethod<[], [bigint[]], "view">;

  getToken: TypedContractMethod<[], [string], "view">;

  getTokenDecimals: TypedContractMethod<[], [bigint], "view">;

  isRemotePool: TypedContractMethod<
    [remoteChainSelector: BigNumberish, remotePoolAddress: BytesLike],
    [boolean],
    "view"
  >;

  isSupportedChain: TypedContractMethod<
    [remoteChainSelector: BigNumberish],
    [boolean],
    "view"
  >;

  isSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  typeAndVersion: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addRemotePool"
  ): TypedContractMethod<
    [remoteChainSelector: BigNumberish, remotePoolAddress: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "applyAllowListUpdates"
  ): TypedContractMethod<
    [removes: AddressLike[], adds: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "applyChainUpdates"
  ): TypedContractMethod<
    [
      remoteChainSelectorsToRemove: BigNumberish[],
      chainsToAdd: {
        remoteChainSelector: BigNumberish;
        remotePoolAddresses: BytesLike[];
        remoteTokenAddress: BytesLike;
        outboundRateLimiterConfig: {
          isEnabled: boolean;
          capacity: BigNumberish;
          rate: BigNumberish;
        };
        inboundRateLimiterConfig: {
          isEnabled: boolean;
          capacity: BigNumberish;
          rate: BigNumberish;
        };
      }[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllowList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllowListEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getCurrentInboundRateLimiterState"
  ): TypedContractMethod<
    [remoteChainSelector: BigNumberish],
    [
      [bigint, bigint, boolean, bigint, bigint] & {
        tokens: bigint;
        lastUpdated: bigint;
        isEnabled: boolean;
        capacity: bigint;
        rate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentOutboundRateLimiterState"
  ): TypedContractMethod<
    [remoteChainSelector: BigNumberish],
    [
      [bigint, bigint, boolean, bigint, bigint] & {
        tokens: bigint;
        lastUpdated: bigint;
        isEnabled: boolean;
        capacity: bigint;
        rate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRateLimitAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRemotePools"
  ): TypedContractMethod<
    [remoteChainSelector: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemoteToken"
  ): TypedContractMethod<[remoteChainSelector: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getRmnProxy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSupportedChains"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRemotePool"
  ): TypedContractMethod<
    [remoteChainSelector: BigNumberish, remotePoolAddress: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSupportedChain"
  ): TypedContractMethod<
    [remoteChainSelector: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "typeAndVersion"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AllowListAdd"
  ): TypedContractEvent<
    AllowListAddEvent.InputTuple,
    AllowListAddEvent.OutputTuple,
    AllowListAddEvent.OutputObject
  >;
  getEvent(
    key: "AllowListRemove"
  ): TypedContractEvent<
    AllowListRemoveEvent.InputTuple,
    AllowListRemoveEvent.OutputTuple,
    AllowListRemoveEvent.OutputObject
  >;
  getEvent(
    key: "Burned"
  ): TypedContractEvent<
    BurnedEvent.InputTuple,
    BurnedEvent.OutputTuple,
    BurnedEvent.OutputObject
  >;
  getEvent(
    key: "ChainAdded"
  ): TypedContractEvent<
    ChainAddedEvent.InputTuple,
    ChainAddedEvent.OutputTuple,
    ChainAddedEvent.OutputObject
  >;
  getEvent(
    key: "ChainConfigured"
  ): TypedContractEvent<
    ChainConfiguredEvent.InputTuple,
    ChainConfiguredEvent.OutputTuple,
    ChainConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "ChainRemoved"
  ): TypedContractEvent<
    ChainRemovedEvent.InputTuple,
    ChainRemovedEvent.OutputTuple,
    ChainRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ConfigChanged"
  ): TypedContractEvent<
    ConfigChangedEvent.InputTuple,
    ConfigChangedEvent.OutputTuple,
    ConfigChangedEvent.OutputObject
  >;
  getEvent(
    key: "Locked"
  ): TypedContractEvent<
    LockedEvent.InputTuple,
    LockedEvent.OutputTuple,
    LockedEvent.OutputObject
  >;
  getEvent(
    key: "Minted"
  ): TypedContractEvent<
    MintedEvent.InputTuple,
    MintedEvent.OutputTuple,
    MintedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested"
  ): TypedContractEvent<
    OwnershipTransferRequestedEvent.InputTuple,
    OwnershipTransferRequestedEvent.OutputTuple,
    OwnershipTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RateLimitAdminSet"
  ): TypedContractEvent<
    RateLimitAdminSetEvent.InputTuple,
    RateLimitAdminSetEvent.OutputTuple,
    RateLimitAdminSetEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;
  getEvent(
    key: "RemotePoolAdded"
  ): TypedContractEvent<
    RemotePoolAddedEvent.InputTuple,
    RemotePoolAddedEvent.OutputTuple,
    RemotePoolAddedEvent.OutputObject
  >;
  getEvent(
    key: "RemotePoolRemoved"
  ): TypedContractEvent<
    RemotePoolRemovedEvent.InputTuple,
    RemotePoolRemovedEvent.OutputTuple,
    RemotePoolRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RouterUpdated"
  ): TypedContractEvent<
    RouterUpdatedEvent.InputTuple,
    RouterUpdatedEvent.OutputTuple,
    RouterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensConsumed"
  ): TypedContractEvent<
    TokensConsumedEvent.InputTuple,
    TokensConsumedEvent.OutputTuple,
    TokensConsumedEvent.OutputObject
  >;

  filters: {
    "AllowListAdd(address)": TypedContractEvent<
      AllowListAddEvent.InputTuple,
      AllowListAddEvent.OutputTuple,
      AllowListAddEvent.OutputObject
    >;
    AllowListAdd: TypedContractEvent<
      AllowListAddEvent.InputTuple,
      AllowListAddEvent.OutputTuple,
      AllowListAddEvent.OutputObject
    >;

    "AllowListRemove(address)": TypedContractEvent<
      AllowListRemoveEvent.InputTuple,
      AllowListRemoveEvent.OutputTuple,
      AllowListRemoveEvent.OutputObject
    >;
    AllowListRemove: TypedContractEvent<
      AllowListRemoveEvent.InputTuple,
      AllowListRemoveEvent.OutputTuple,
      AllowListRemoveEvent.OutputObject
    >;

    "Burned(address,uint256)": TypedContractEvent<
      BurnedEvent.InputTuple,
      BurnedEvent.OutputTuple,
      BurnedEvent.OutputObject
    >;
    Burned: TypedContractEvent<
      BurnedEvent.InputTuple,
      BurnedEvent.OutputTuple,
      BurnedEvent.OutputObject
    >;

    "ChainAdded(uint64,bytes,tuple,tuple)": TypedContractEvent<
      ChainAddedEvent.InputTuple,
      ChainAddedEvent.OutputTuple,
      ChainAddedEvent.OutputObject
    >;
    ChainAdded: TypedContractEvent<
      ChainAddedEvent.InputTuple,
      ChainAddedEvent.OutputTuple,
      ChainAddedEvent.OutputObject
    >;

    "ChainConfigured(uint64,tuple,tuple)": TypedContractEvent<
      ChainConfiguredEvent.InputTuple,
      ChainConfiguredEvent.OutputTuple,
      ChainConfiguredEvent.OutputObject
    >;
    ChainConfigured: TypedContractEvent<
      ChainConfiguredEvent.InputTuple,
      ChainConfiguredEvent.OutputTuple,
      ChainConfiguredEvent.OutputObject
    >;

    "ChainRemoved(uint64)": TypedContractEvent<
      ChainRemovedEvent.InputTuple,
      ChainRemovedEvent.OutputTuple,
      ChainRemovedEvent.OutputObject
    >;
    ChainRemoved: TypedContractEvent<
      ChainRemovedEvent.InputTuple,
      ChainRemovedEvent.OutputTuple,
      ChainRemovedEvent.OutputObject
    >;

    "ConfigChanged(tuple)": TypedContractEvent<
      ConfigChangedEvent.InputTuple,
      ConfigChangedEvent.OutputTuple,
      ConfigChangedEvent.OutputObject
    >;
    ConfigChanged: TypedContractEvent<
      ConfigChangedEvent.InputTuple,
      ConfigChangedEvent.OutputTuple,
      ConfigChangedEvent.OutputObject
    >;

    "Locked(address,uint256)": TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;
    Locked: TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;

    "Minted(address,address,uint256)": TypedContractEvent<
      MintedEvent.InputTuple,
      MintedEvent.OutputTuple,
      MintedEvent.OutputObject
    >;
    Minted: TypedContractEvent<
      MintedEvent.InputTuple,
      MintedEvent.OutputTuple,
      MintedEvent.OutputObject
    >;

    "OwnershipTransferRequested(address,address)": TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;
    OwnershipTransferRequested: TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RateLimitAdminSet(address)": TypedContractEvent<
      RateLimitAdminSetEvent.InputTuple,
      RateLimitAdminSetEvent.OutputTuple,
      RateLimitAdminSetEvent.OutputObject
    >;
    RateLimitAdminSet: TypedContractEvent<
      RateLimitAdminSetEvent.InputTuple,
      RateLimitAdminSetEvent.OutputTuple,
      RateLimitAdminSetEvent.OutputObject
    >;

    "Released(address,address,uint256)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;

    "RemotePoolAdded(uint64,bytes)": TypedContractEvent<
      RemotePoolAddedEvent.InputTuple,
      RemotePoolAddedEvent.OutputTuple,
      RemotePoolAddedEvent.OutputObject
    >;
    RemotePoolAdded: TypedContractEvent<
      RemotePoolAddedEvent.InputTuple,
      RemotePoolAddedEvent.OutputTuple,
      RemotePoolAddedEvent.OutputObject
    >;

    "RemotePoolRemoved(uint64,bytes)": TypedContractEvent<
      RemotePoolRemovedEvent.InputTuple,
      RemotePoolRemovedEvent.OutputTuple,
      RemotePoolRemovedEvent.OutputObject
    >;
    RemotePoolRemoved: TypedContractEvent<
      RemotePoolRemovedEvent.InputTuple,
      RemotePoolRemovedEvent.OutputTuple,
      RemotePoolRemovedEvent.OutputObject
    >;

    "RouterUpdated(address,address)": TypedContractEvent<
      RouterUpdatedEvent.InputTuple,
      RouterUpdatedEvent.OutputTuple,
      RouterUpdatedEvent.OutputObject
    >;
    RouterUpdated: TypedContractEvent<
      RouterUpdatedEvent.InputTuple,
      RouterUpdatedEvent.OutputTuple,
      RouterUpdatedEvent.OutputObject
    >;

    "TokensConsumed(uint256)": TypedContractEvent<
      TokensConsumedEvent.InputTuple,
      TokensConsumedEvent.OutputTuple,
      TokensConsumedEvent.OutputObject
    >;
    TokensConsumed: TypedContractEvent<
      TokensConsumedEvent.InputTuple,
      TokensConsumedEvent.OutputTuple,
      TokensConsumedEvent.OutputObject
    >;
  };
}
